language: go
sudo: false
go:
  - 1.6.0
  - 1.7.0
  - 1.8.0
  - 1.9.0
  - tip
env:
  global:
    - GOARCH=amd64
script:
  - go list ./... | grep -v vendor | xargs go vet
  - go list ./... | grep -v vendor | xargs go test -v
