language: go
sudo: false
go:
  - 1.12.x
env:
  global:
    - GOARCH=amd64
script:
  # TODO: Create lint
  #- go list ./... | grep -v vendor | xargs go vet
  - go test -v -cover ./...
  - go test -bench . -timeout 1h ./...
