language: go
sudo: false
go:
  - 1.11.x
env:
  global:
    - GOARCH=amd64
script:
  # TODO: Create lint
  #- go list ./... | grep -v vendor | xargs go vet
  - go list ./... | grep -v vendor | xargs go test -v
