language: go
sudo: false
go:
  - 1.12.x
env:
  global:
    - GOARCH=amd64
    - GO111MODULE=on
script:
  # TODO: Create lint
  #- go list ./... | grep -v vendor | xargs go vet
  - go test -v -cover -mod=vendor ./...
  - go test -mod=vendor -bench . -timeout 1h ./...
